name: review
on: 
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - run: yarn install
      - run: yarn lint
      - name: Failed to lint
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: The commit was failed to push by ${{ github.actor }} due to issue with "lint"
  update:
    needs: [lint]
    name: Update status
    runs-on: ubuntu-latest
    steps:
    - name: Update in telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |  #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
          New ${{ github.event_name }} commit in ${{ github.ref }} branch by "${{ github.actor }}".
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
